# Generated by Django 4.1.1 on 2022-10-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to='infocar/%Y-%m-$d/', verbose_name='Фото'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='auto',
            name='complectations',
            field=models.ManyToManyField(blank='True', null='True', to='infocar.complectation', verbose_name='Комплектация'),
        ),
    ]
